# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vector_map/waypoints_array.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import vector_map.msg

class waypoints_array(genpy.Message):
  _md5sum = "5dd85112a2219703725eb3991320c5ee"
  _type = "vector_map/waypoints_array"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """waypoint_publish[] waypoints
================================================================================
MSG: vector_map/waypoint_publish
int32 id
int32 lane_id
float32 x
float32 y
float32 z
int32 point_id
"""
  __slots__ = ['waypoints']
  _slot_types = ['vector_map/waypoint_publish[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       waypoints

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(waypoints_array, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.waypoints is None:
        self.waypoints = []
    else:
      self.waypoints = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.waypoints)
      buff.write(_struct_I.pack(length))
      for val1 in self.waypoints:
        _x = val1
        buff.write(_get_struct_2i3fi().pack(_x.id, _x.lane_id, _x.x, _x.y, _x.z, _x.point_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.waypoints is None:
        self.waypoints = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.waypoints = []
      for i in range(0, length):
        val1 = vector_map.msg.waypoint_publish()
        _x = val1
        start = end
        end += 24
        (_x.id, _x.lane_id, _x.x, _x.y, _x.z, _x.point_id,) = _get_struct_2i3fi().unpack(str[start:end])
        self.waypoints.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.waypoints)
      buff.write(_struct_I.pack(length))
      for val1 in self.waypoints:
        _x = val1
        buff.write(_get_struct_2i3fi().pack(_x.id, _x.lane_id, _x.x, _x.y, _x.z, _x.point_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.waypoints is None:
        self.waypoints = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.waypoints = []
      for i in range(0, length):
        val1 = vector_map.msg.waypoint_publish()
        _x = val1
        start = end
        end += 24
        (_x.id, _x.lane_id, _x.x, _x.y, _x.z, _x.point_id,) = _get_struct_2i3fi().unpack(str[start:end])
        self.waypoints.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2i3fi = None
def _get_struct_2i3fi():
    global _struct_2i3fi
    if _struct_2i3fi is None:
        _struct_2i3fi = struct.Struct("<2i3fi")
    return _struct_2i3fi
