# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from points_msgs/points_density.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class points_density(genpy.Message):
  _md5sum = "7c990c22312891c33f02a93bc686cb7f"
  _type = "points_msgs/points_density"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 points_num 
float32 points_int
float64 dist_num """
  __slots__ = ['points_num','points_int','dist_num']
  _slot_types = ['int32','float32','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       points_num,points_int,dist_num

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(points_density, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.points_num is None:
        self.points_num = 0
      if self.points_int is None:
        self.points_int = 0.
      if self.dist_num is None:
        self.dist_num = 0.
    else:
      self.points_num = 0
      self.points_int = 0.
      self.dist_num = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_ifd().pack(_x.points_num, _x.points_int, _x.dist_num))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.points_num, _x.points_int, _x.dist_num,) = _get_struct_ifd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_ifd().pack(_x.points_num, _x.points_int, _x.dist_num))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.points_num, _x.points_int, _x.dist_num,) = _get_struct_ifd().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_ifd = None
def _get_struct_ifd():
    global _struct_ifd
    if _struct_ifd is None:
        _struct_ifd = struct.Struct("<ifd")
    return _struct_ifd
