# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from points_msgs/points_density_array.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import points_msgs.msg

class points_density_array(genpy.Message):
  _md5sum = "b858f0c0e7e13b1ca36b528932bc5670"
  _type = "points_msgs/points_density_array"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """points_density[] points_density_array
================================================================================
MSG: points_msgs/points_density
int32 points_num 
float32 points_int
float64 dist_num """
  __slots__ = ['points_density_array']
  _slot_types = ['points_msgs/points_density[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       points_density_array

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(points_density_array, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.points_density_array is None:
        self.points_density_array = []
    else:
      self.points_density_array = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.points_density_array)
      buff.write(_struct_I.pack(length))
      for val1 in self.points_density_array:
        _x = val1
        buff.write(_get_struct_ifd().pack(_x.points_num, _x.points_int, _x.dist_num))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.points_density_array is None:
        self.points_density_array = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.points_density_array = []
      for i in range(0, length):
        val1 = points_msgs.msg.points_density()
        _x = val1
        start = end
        end += 16
        (_x.points_num, _x.points_int, _x.dist_num,) = _get_struct_ifd().unpack(str[start:end])
        self.points_density_array.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.points_density_array)
      buff.write(_struct_I.pack(length))
      for val1 in self.points_density_array:
        _x = val1
        buff.write(_get_struct_ifd().pack(_x.points_num, _x.points_int, _x.dist_num))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.points_density_array is None:
        self.points_density_array = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.points_density_array = []
      for i in range(0, length):
        val1 = points_msgs.msg.points_density()
        _x = val1
        start = end
        end += 16
        (_x.points_num, _x.points_int, _x.dist_num,) = _get_struct_ifd().unpack(str[start:end])
        self.points_density_array.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_ifd = None
def _get_struct_ifd():
    global _struct_ifd
    if _struct_ifd is None:
        _struct_ifd = struct.Struct("<ifd")
    return _struct_ifd
