// Generated by gencpp from file points_msgs/plane_coefficients.msg
// DO NOT EDIT!


#ifndef POINTS_MSGS_MESSAGE_PLANE_COEFFICIENTS_H
#define POINTS_MSGS_MESSAGE_PLANE_COEFFICIENTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace points_msgs
{
template <class ContainerAllocator>
struct plane_coefficients_
{
  typedef plane_coefficients_<ContainerAllocator> Type;

  plane_coefficients_()
    : a(0.0)
    , b(0.0)
    , c(0.0)
    , d(0.0)  {
    }
  plane_coefficients_(const ContainerAllocator& _alloc)
    : a(0.0)
    , b(0.0)
    , c(0.0)
    , d(0.0)  {
  (void)_alloc;
    }



   typedef double _a_type;
  _a_type a;

   typedef double _b_type;
  _b_type b;

   typedef double _c_type;
  _c_type c;

   typedef double _d_type;
  _d_type d;





  typedef boost::shared_ptr< ::points_msgs::plane_coefficients_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::points_msgs::plane_coefficients_<ContainerAllocator> const> ConstPtr;

}; // struct plane_coefficients_

typedef ::points_msgs::plane_coefficients_<std::allocator<void> > plane_coefficients;

typedef boost::shared_ptr< ::points_msgs::plane_coefficients > plane_coefficientsPtr;
typedef boost::shared_ptr< ::points_msgs::plane_coefficients const> plane_coefficientsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::points_msgs::plane_coefficients_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::points_msgs::plane_coefficients_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace points_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'points_msgs': ['/home/ee904-i5-old-pc-1/Desktop/Kenny/catkin_ws/src/points_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::points_msgs::plane_coefficients_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::points_msgs::plane_coefficients_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::points_msgs::plane_coefficients_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::points_msgs::plane_coefficients_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::points_msgs::plane_coefficients_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::points_msgs::plane_coefficients_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::points_msgs::plane_coefficients_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5c1b8d0c23e6e29f5d8d9fbdb957dac";
  }

  static const char* value(const ::points_msgs::plane_coefficients_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5c1b8d0c23e6e29ULL;
  static const uint64_t static_value2 = 0xf5d8d9fbdb957dacULL;
};

template<class ContainerAllocator>
struct DataType< ::points_msgs::plane_coefficients_<ContainerAllocator> >
{
  static const char* value()
  {
    return "points_msgs/plane_coefficients";
  }

  static const char* value(const ::points_msgs::plane_coefficients_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::points_msgs::plane_coefficients_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 a\n\
float64 b\n\
float64 c\n\
float64 d\n\
";
  }

  static const char* value(const ::points_msgs::plane_coefficients_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::points_msgs::plane_coefficients_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
      stream.next(m.c);
      stream.next(m.d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct plane_coefficients_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::points_msgs::plane_coefficients_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::points_msgs::plane_coefficients_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<double>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<double>::stream(s, indent + "  ", v.b);
    s << indent << "c: ";
    Printer<double>::stream(s, indent + "  ", v.c);
    s << indent << "d: ";
    Printer<double>::stream(s, indent + "  ", v.d);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POINTS_MSGS_MESSAGE_PLANE_COEFFICIENTS_H
